[build]
  base = "frontend"
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps --force && npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  SECRETS_SCAN_ENABLED = "false"

# Disable secrets scanning to prevent false positives
[build.processing]
  skip_processing = false

# Disable secrets scanning entirely to prevent false positives
[build.processing.secrets]
  enabled = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
