services:
  - type: web
    name: budget-tracker-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE_DAYS
        value: "7"
      - key: API_PORT
        value: "8000"
      - key: DEBUG
        value: "1"
